### ISSUE TITLE
Left panel: remotes should be collapsed

### ISSUE THREAD

**Issue by pmiossec** [EbenZhang/gitextensions#13]
I think that the behavior that is the one of the left panel could be improved a little...
Expanding all the remotes branches could be a little overwhelming if you have some remotes and that there is some branches. I think it could be better if all the remotes branches are collapsed (like tags are) letting just displayed the remotes name.

You could see what I describe here: 

![gitextensions_leftpanel](https://cloud.githubusercontent.com/assets/460196/10868899/7cea60c4-809d-11e5-8421-ad8e8bc7affd.jpg)

**Comment by EbenZhang** [comment]
I find this issue as well. I will make the changes.

**Comment by EbenZhang** [comment]
Fixed in 14cb981995934e225eefb94faea60c84f7ea403
