### ISSUE TITLE
Assert; "Found lone \r, data consistency problems?"

### ISSUE THREAD

**Issue by TamaMcGlinn** [EbenZhang/gitextensions#37]
Unfortunately, the program is unusable to me because this assertion fails all the time. I'm trying to find out what triggers it but it seems to happen sometimes when I refresh the page or open the commit window - not sure what git status triggers it.

![](http://i.imgur.com/wvAF4CS.png)

**Comment by EbenZhang** [comment]
This is a bug someone just fixed yesterday in the main repo. I will merge that down and update you.

**Comment by EbenZhang** [comment]
Please try the `GitExtensions-2.49.99.7-Setup.msi` in this release: https://github.com/EbenZhang/gitextensions/releases/latest

**Comment by TamaMcGlinn** [comment]
Thank you for merging and building that update. 
Even before I updated, on the PC where I had this issue, I stopped getting the data consistency problems, which is strange. I've now done the exact same steps I originally did but with the new installer, and also did not get this issue prop up.
So I think this issue can be closed.

**Comment by EbenZhang** [comment]
> I stopped getting the data consistency problems

The issue is specific to the file which uses `\r` as the end of line.
