### ISSUE TITLE
Recreated tag doesn't get updated

### ISSUE THREAD

**Issue by FizzBuzz791** [EbenZhang/gitextensions#65]
Steps to repro;
1. Create a tag on Commit X and push to server.
2. Perform a Fetch to ensure it's on the server.
3. Delete tag from server.
4. Recreate the exact same tag on a different commit (Commit Y)....
5. Perform a Fetch. Observe that tag is still on the original commit (Commit X). **Expected the tag to be on Commit Y.**
6. Delete local tag and do another Fetch. **Tag is now visible on Commit Y.**

Hope the above makes sense. I was actually manually creating/deleting the tag via Visual Studio Online web interface, rather than the command line or Git Ext, but I don't think that matters as the web interface is essentially the server, there's no concept of local. 

Version: 2.50.17.99

**Comment by EbenZhang** [comment]
It's probably not an issue with GitExtensions, I believe (didn't try myself) git command line won't update the tag either.

**Comment by EbenZhang** [comment]
The team needs to do delete the local tag if a tag is changed, at the server side, to reference another commit. The follow bash commands can help delete all local tags and fetch from the server.

```
git tag -l | xargs git tag -d
git fetch
```

**Comment by FizzBuzz791** [comment]
I wondered if that might be the case, thanks for the info.
